KGID/Controllers/MotorInsuranceController.cs
using BLL.KGIDMotorInsurance;
using BLL.KGIDMIMasterBLL;
using Common;
using KGID_Models.KGID_VerifyData;
using KGID_Models.KGIDMotorInsurance;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text.pdf;
using KGID_Models.KGID_Policy;
using System.Net;
/// <KII_Integration_References>
using com.sun.org.apache.xml.@internal.security.c14n;
using com.sun.org.apache.xml.@internal.security.utils;
using java.io;
using java.security;
using javax.crypto;
using javax.crypto.spec;
using javax.xml.stream;
using javax.xml.stream.events;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using System.Net.Cache;
using log4net;
using DLL.DBConnection;
using KGID_Models.KGID_Master;

using Renci.SshNet;
using System.Data;
using System.Diagnostics;
using System.Threading;
using System.Web.Configuration;
using KGID_Models.NBApplication;

namespace KGID.Controllers
{

    public class MotorInsuranceController : Controller
    {

        private readonly IMotorInsuranceProposerDetailsBll _IMotorInsuranceProposerDetailsBll;
        private readonly IMotorInsuranceVehicleDetailsBll _IMotorInsuranceVehicleDetailsBll;
        private readonly IMotorInsuranceRenewalDetailsBll _IMotorInsuranceRenewalDetailsBll;

        public MotorInsuranceController()
        {
            this._IMotorInsuranceProposerDetailsBll = new MotorInsuranceProposerDetailsBll();
            this._IMotorInsuranceVehicleDetailsBll = new MotorInsuranceVehicleDetailsBll();
            this._IMotorInsuranceRenewalDetailsBll = new MotorInsuranceRenewalDetailsBll();
        }

        // GET: MotorInsurance
        public ActionResult Index()
        {
            return View();
        }
        //[HttpGet]
        [Route("mi-e-fa")]
        public ActionResult MotorInsuranceEmployeeApplication()
        {
            Session.Remove("RID");
            string result = _IMotorInsuranceVehicleDetailsBll.GetEmployeeLoanDetails(Convert.ToInt64(Session["UID"]));
            if (result == "")
            {
                result = "1";
            }


            if (result == "1" || result == "2")
            {
                return View();
            }
            else if (result == "3" || result == "5" || result == "7" || result == "11" || result == "15")
            {
                return RedirectToAction("MotorInsuranceStatusOfApplication");
            }
            else
            {
                VM_MIApplicationDetails obj = new VM_MIApplicationDetails();
                ViewBag.Message = String.Format("Not eligible,will be applicable only for loan taken employees");
                return View(obj);
            }

        }

        //[HttpGet]
        [Route("mi-dpt-faf/{PageType?}/{refNo?}/{category?}")]
        [Route("mi-agy-fa/{PageType?}/{refNo?}/{category?}")]
        [Route("mi-loa-edt-apln/{PageType?}/{refNo?}/{category?}/{status?}")]
        [Route("mi-soa-edt-apln/{PageType?}/{refNo?}/{category?}")]
        public ActionResult MotorInsuranceApplication(string PageType = null, long refNo = 0, string category = "", int status = 0)
        {
            Session["RID"] = (refNo != 0) ? refNo : 0;

            VM_MIApplicationDetails obj = new VM_MIApplicationDetails();

            obj.Type = Convert.ToString((PageType == "empty") ? "" : PageType);
            if (status == 2)
            {
                obj.SentBackAppliaction = 1;
            }
            else if (status == 94)
            {
                obj.SentBackAppliaction = 94;
            }
            else
            {
                obj.SentBackAppliaction = 0;
            }

            return View(obj);
        }

        //=========================View Data related functions ================================
        #region View Data related functions
        //[HttpGet]
        // [Route("ProposerDetailsToView")]
        public ActionResult ProposerDetailsToView(string PageType, string refNo = "")
        {
            VM_MotorInsuranceProposerDetails _ProposerDetail = new VM_MotorInsuranceProposerDetails();
            try
            {
                if (Convert.ToInt32(Session["SelectedCategory"]) == 2)
                {
                    _ProposerDetail = _IMotorInsuranceProposerDetailsBll.MIProposerDetailsBll(Convert.ToInt64(Session["UID"]), (PageType == null) ? "" : PageType, (Convert.ToInt64(Session["RID"]) == 0) ? 0 : Convert.ToInt64(Session["RID"]), Convert.ToInt32(Session["SelectedCategory"]));
                }
                else if (Session["Categories"] != null && Session["Categories"].ToString().Contains(Convert.ToString((int)UserCategories.AGENCY)))
                {
                    _ProposerDetail = _IMotorInsuranceProposerDetailsBll.MIProposerDetailsBll(Convert.ToInt64(Session["UID"]), (PageType == null) ? "" : PageType, (Convert.ToInt64(Session["RID"]) == 0) ? 0 : Convert.ToInt64(Session["RID"]), Convert.ToInt32(Session["Categories"]));
                }
                else if (Convert.ToInt32(Session["SelectedCategory"]) == 1)
                {
                    _ProposerDetail = _IMotorInsuranceProposerDetailsBll.MIProposerDetailsBll(Convert.ToInt64(Session["UID"]), "Emp", (Convert.ToInt64(Session["RID"]) == 0) ? 0 : Convert.ToInt64(Session["RID"]), Convert.ToInt32(Session["SelectedCategory"]));
                }
                else if (Session["MBVALUE"] != null && Convert.ToBoolean(Session["MBVALUE"]) == true)
                {
                    _ProposerDetail = _IMotorInsuranceProposerDetailsBll.MIProposerDetailsBll(Convert.ToInt64(Session["UID"]), (PageType == null) ? "" : PageType, (Convert.ToInt64(Session["RID"]) == 0) ? 0 : Convert.ToInt64(Session["RID"]), Convert.ToInt32(Session["Categories"]));
                }
                

            }
            catch (Exception ex)
            {

            }

            if (!String.IsNullOrEmpty(_ProposerDetail.mipd_kgid_application_number))
            {
                Session["RID"] = _ProposerDetail.mipd_kgid_application_number;
                TempData["Deptmartment"] = _ProposerDetail.mipd_Department;
                using (MemoryStream ms = new MemoryStream())
                {
                    QRCodeGenerator qrGenerator = new QRCodeGenerator();
                    QRCodeGenerator.QRCode qrCode = qrGenerator.CreateQrCode(_ProposerDetail.mipd_kgid_application_number.ToString(), QRCodeGenerator.ECCLevel.Q);
                    using (Bitmap bitMap = qrCode.GetGraphic(20))
                    {
                        bitMap.Save(ms, ImageFormat.Png);
                        _ProposerDetail.QRCode = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                    }
                }
            }
            return this.PartialView("_ProposerDetails", _ProposerDetail);
        }
        //[HttpGet]
        //[Route("VehicleDetailsToView")]
        public ActionResult VehicleDetailsToView()
        {
            VM_MotorInsuranceVehicleDetails _VehicleDetails = _IMotorInsuranceVehicleDetailsBll.GetMIVehicleDetails(Convert.ToInt64(Session["UID"]), Convert.ToInt64(Session["RID"]));

            if (_VehicleDetails.mipd_type_of_cover_id != 0)
            {
                if (_VehicleDetails.mipd_type_of_cover_id == 3)
                {
                    _VehicleDetails.mipd_type_of_cover_list = _VehicleDetails.mipd_type_of_cover_list.Where(a => a.Value == "3").Select(a => a).ToList();
                }
                else if (_VehicleDetails.mipd_type_of_cover_id != 2 || _VehicleDetails.mipd_type_of_cover_id != 1)
                {
                    _VehicleDetails.mipd_type_of_cover_list = _VehicleDetails.mipd_type_of_cover_list.Where(a => a.Value != "3").Select(a => a).ToList();
                }
                else
                {
                    _VehicleDetails.mipd_type_of_cover_list = _VehicleDetails.mipd_type_of_cover_list;
                }
            }

            return this.PartialView("_VehicleDetails", _VehicleDetails);
        }

        public string CheckVehicleExists(VM_MotorInsuranceVehicleDetails details)
        {
            string isMatching = "";
            string chassisNo = details.mivd_chasis_no;
            string EngineNo = details.mivd_engine_no;
            string result = _IMotorInsuranceVehicleDetailsBll.CheckVehicleExists(chassisNo, EngineNo);
            if (result != "")
            {
                string[] resultsplit = result.Split('$');
                if (resultsplit.Length > 0)
                {
                    foreach (var item in resultsplit)
                    {
                        if (item != "0")
                        {
                            string[] ref_off = item.Split('~');
                            if (ref_off[1] == Convert.ToString(Session["UID"]))
                            {
                                if (ref_off[0] == Convert.ToString(Session["RID"]))
                                {

                                    isMatching = "yes" + "@";
                                }
                                else
                                {
                                    isMatching = "no" + "@ref";
                                }

                            }
                            else
                            {
                                isMatching = "no" + "@usid@" + ref_off[2];
                            }
                        }
                        else
                        {

                            if (item == Convert.ToString(Session["RID"]) || item == "0")
                            {
                                isMatching = "yes";
                            }
                            else
                            {

KGID/Views/MotorInsurance/MotorInsuranceStatusOfRenewalApplication.cshtml
@model KGID_Models.KGIDMotorInsurance.VM_DDOVerificationDetailsMI
@{
    ViewBag.Title = "MotorInsuranceStatusOfRenewalApplication";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">

    .nav-tabs .nav-item.show .nav-link, .nav-tabs .nav-link.active {
        color: #ffffff !important;
        background-color: #2184bed1 !important;
        border-color: #dee2e6 #dee2e6 #2184be !important;
        font-size: 14px;
        font-weight: 400;
        cursor: pointer !important;
    }
    td a{
        color:blue;
        text-decoration:underline;
    }
    
    #navmenu .nav-link {
        border: 1px solid #d8d8d885 !important;
        margin: .5px;
    }
    table{
        text-align:center;
    }
</style>
<script src="~/Content/amcharts/amcharts.js"></script>
<script src="~/Content/amcharts/pie.js"></script>

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-12 text-center">
                        <h3>Motor Insurance Status of Renewal Application</h3>
                    </div>
                </div>

            </div>

            <div class="card-body">

                <div id="divCurrentStatus" class="application-tab">
                    <section>
                        <div class="row">
                            <div class="col-12">
                                @*<div class="form-group">
                                        <h6 class="font-weight-bold">Application Status</h6>
                                    </div>*@
                                <table class="table table-striped table-bordered" id="tblMIDDOApplicationStatus" cellspacing="0">
                                    <thead style="background: #308385;color: #fff;">
                                        <tr>
                                            <th>Serial no</th>
                                            <th>Application Reference Number</th>
                                            <th>Type of Cover</th>
                                            <th>Registration No.</th>
                                            <th>Chassis No.</th>
                                            <th>Engine No.</th>
                                            <th>Year of Manufacture</th>
                                            @*<th>Vehicle Manufacturer</th>*@
                                            <th>Vehicle Model</th>
                                            <th>Policy Number</th>
                                            @*<th>MI Bond</th>*@
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.ViewStatusForEmployees != null && Model.ViewStatusForEmployees.Count > 0)
                                        {
                                            var rowcount = 1;
                                            foreach (var item in Model.ViewStatusForEmployees)
                                            {
                                        <tr>
                                            @*<td>@item.EmployeeCode</td>
        <td>@item.Name</td>*@
                                            <td>@rowcount</td>
                                            <td>@item.ApplicationNumber</td>
                                            <td>@item.TypeofCover</td>
                                            <td>@item.registrationNo</td>
                                            <td>@item.ChasisNo</td>
                                            <td>@item.EngineNo</td>
                                            @*<td>@item.Premium</td>*@
                                            @*<td>@item.Status</td>*@
                                            @*<td>
            @if (item.Status == "Approved")
            {
                @Html.ActionLink("View MI Bond", "PrintMIBond", "MotorInsurance", new { AppRefNo = item.ApplicationNumber, AppId = item.ApplicationId, EmpID = item.EmployeeCode }, htmlAttributes: new { @target = "_blank" })
            }
        </td>*@
                                            <td>@item.VehicleYear</td>
                                           
                                            <td>@item.VehicleModelName</td>
                                            <td>@item.PolicyNumber</td>
                                            <td>@item.Status</td>

                                            @*@if (@item.AppStatusID == 15)
        {
            <td>@Html.ActionLink("View MI Bond", "PrintMIBond", "MotorInsurance", new { @Type = "Renewal", AppRefNo = item.ApplicationNumber, AppId = item.ApplicationId, EmpID = item.EmployeeCode }, htmlAttributes: new { @target = "_blank" })</td>
        }
        else
        {
            <td><a href="@Url.Action("MIViewRenewalApplication", "VerifyDetails", new RouteValueDictionary(new { @empId = item.EmployeeCode, applicationId = item.ApplicationId , refNo=item.ApplicationNumber,category=item.CategoryId,PrevRefNo=item.PrevApplicationNumber}))" class="btn btn-info btn-sm" style="font-size: inherit;padding: 0px 1px 1px 1px;">View Application</a></td>
        }*@
                                            @if (@item.AppStatusID == 2 || @item.AppStatusID == 1)
                                            {

                                                @*<td><a href="/mi-soa-edt-apln/empty/@item.ApplicationNumber/@item.CategoryId">Edit Application</a></td>*@
                                            }
                                            else if (@item.AppStatusID == 15)
                                            {
                                                if (item.SignedBondDocPath == "" || item.SignedBondDocPath == null)
                                                {
                                                    <td>

                                                        <a class="OpenMBDocPath" href="javascript:;" data-path="@item.UnsignBondDocPath" data-policynumber="@item.PolicyNumber" data-doctype="Bond" style="text-decoration-color:green"><p style="color:forestgreen;">View Unsigned MB Bond</p></a>
                                                    </td>
                                                }
                                                else
                                                {
                                                    <td>
                                                        <a class="OpenMBDocPath" href="javascript:;" data-path="@item.SignedBondDocPath" data-policynumber="@item.PolicyNumber" data-doctype="Bond">View MB Bond</a>
                                                    </td>
                                                }

                                            }
                                            else
                                            {

                                                @*<td><a href="/mi-soa-vw-apln/@item.EmployeeCode/@item.ApplicationId/@item.ApplicationNumber/@item.CategoryId">View Application</a></td>*@
                                                <td><a href="@Url.Action("MIViewRenewalApplication", "VerifyDetails", new RouteValueDictionary(new { @empId = item.EmployeeCode, applicationId = item.ApplicationId , refNo=item.ApplicationNumber,category=item.CategoryId,PrevRefNo=item.PrevApplicationNumber}))" class="btn btn-info btn-sm" style="font-size: inherit;padding: 0px 1px 1px 1px;">View Application</a></td>
                                            }

                                        </tr>
                                                rowcount++;
                                            }
                                        }
                                        else
                                        {
                                            <tr>
                                                <td colspan="7">
                                                    There is no applications submitted to display.
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        $('#tblMIDDOApplicationStatus').DataTable({
            paging: true,
            info: false,
            ordering: false,
            //aaSorting: [[1, "desc"]],
           // searching: false
         });
    });
    $('.OpenMBDocPath').click(function () {
        debugger;
        var $this = $(this);
        var docpath = $this.data('path');
        var policynumber = $this.data('policynumber');
        var doctype = $this.data('doctype');
        $.ajax({
            url: '/VerifyData/PrintFilePath',
            data: JSON.stringify({ "FilePath": docpath }),
            type: 'POST',
            async: false,
            contentType: 'application/json; charset=utf-8',
            success: function (result) {
                if (result.IsSuccess == true) {
                    var path = result.Result
                    //const linkSource = `data:application/pdf;base64,${path}`;
                    //const downloadLink = document.createElement("a");
                    if (doctype == "Bond") {
                        const fileName = "MBBond_" + policynumber + ".pdf";
                        //downloadLink.href = linkSource;
                        //downloadLink.download = fileName;
                        //downloadLink.click();
                        // Open New Tab
                        printPreview(path)
                        //
                        delete doctype;
                    }
                }
                else {
                    alertify.alert("Unable to get the file..! Please try Again Later..!");
                }
            }
        });
    });
</script>

KGID/Views/MotorInsurance/_ProposerDetails.cshtml
@model KGID_Models.KGIDMotorInsurance.VM_MotorInsuranceProposerDetails

<style>
	
	div#divMIProposerDetails {
		color: black;
	}
    input, textarea#txtOwnerofVehicle {
        background: #e8f0fe;
    }

        input#txtPEmail {
            background: #e8f0fe;
        }

        input#txtPPinCode {
            background: #e8f0fe;
        }
</style>
<script src="~/Scripts/KGIDMotorInsurance/MotorInsurance.js"></script>
<div id="divMIProposerDetails" data-submit-url="@Url.Action("InsertMIAppnReferenceno", "MotorInsurance", new { area = "" })">
    @*@Html.HiddenFor(model => model.mipd_kgid_application_number, new { id = "hdnMIReferanceNo" })*@
    @Html.HiddenFor(model => model.mipd_kgid_application_number, new { id = "hdnMIReferanceNo" })
    @Html.HiddenFor(m => m.QRCode, new { id = "hdnQRCode" })
    @Html.HiddenFor(m => m.PolicyNumber, new { id = "hPolicyNo" })

    <div class="row" id="divShowQRCode" style="display:none;">
        <div class="form-group col-6">
            Reference Number : <b><span id="spnBReferanceNo"></span></b>
        </div>
        <div class="form-group col-6" id="refNo" style="display:none;">
            @if (@Html.DisplayFor(model => model.QRCode) != null)
            {
                <img src="@Html.DisplayFor(model => model.QRCode)" id="imgBQRCode" alt="" style="height:150px;width:150px" />
            }
            else
            {
                <img src="" id="imgBQRCode" alt="" style="height:150px;width:150px" />
            }

        </div>
    </div>
    <div class="row">
        <div class="form-group col-6">
            <label for="lblPProposerName" class="control-label field-required">
                Proposer's( Owner’s) Full Name :
            </label>
            @Html.TextBoxFor(model => model.mipd_proposer_fullname, new { @class = "form-control ", @id = "txtPProposerFullName", @readonly = "readonly" })
        </div>
        <div class="form-group col-6">
            <label for="lblOwnerofTheVehicle" class="control-label field-required">Owner of the Vehicle :</label>
            @Html.TextAreaFor(model => model.OwnerofTheVehicle, new { @class = "form-control", @id = "txtOwnerofVehicle" })
            @Html.ValidationMessageFor(m => m.OwnerofTheVehicle, "Please enter Owner of The Vehicle.", new { @class = "text-danger col-form-label-sm err", id = "errOwnerofVehicle", hidden = "hidden" })
        </div>
    </div>

    <div class="row">
        <div class="form-group col-6">
            <label for="lblPAddress" class="control-label field-required">Address (Address where vehicle  is normally kept and used ) :</label>
            @Html.TextAreaFor(model => model.mipd_address, new { @class = "form-control", @id = "txtPAddress", @maxlength = "200", @style = "max-height: 120px;" })
            @Html.ValidationMessageFor(m => m.mipd_address, "Please enter address.", new { @class = "text-danger col-form-label-sm err", id = "errVDAddressReq", hidden = "hidden" })
        </div>
        <div class="form-group col-3">
            <label for="lblPEmail" class="control-label field-required">Email :</label>
            @Html.TextBoxFor(model => model.mipd_email, new { @class = "form-control", @id = "txtPEmail" })
            @Html.ValidationMessageFor(m => m.mipd_email, "Please enter email.", new { @class = "text-danger col-form-label-sm err", id = "errVDEmailReq", hidden = "hidden" })

        </div>
        <div class="form-group col-3">
            <label for="lblPPinCode" class="control-label field-required">Pincode :</label>
            @Html.TextBoxFor(model => model.mipd_pincode, new { @class = "form-control ClNum numbersonly", @maxlength = "6", @id = "txtPPinCode" })
            @Html.ValidationMessageFor(m => m.mipd_pincode, "Please enter valid pincode.", new { @class = "text-danger col-form-label-sm err", id = "errVDPinCodeReq", hidden = "hidden" })

        </div>
        @*<div class="form-group col-6">
                <label for="lblPFaxNo" class="control-label field-required">Fax No :</label>
                @Html.TextBoxFor(model => model.mipd_fax_no, new { @class = "form-control numbersonly", @id = "txtPFaxNo", @maxlength = "10" })
                @Html.ValidationMessageFor(m => m.mipd_fax_no, "Please enter valid fax number.", new { @class = "text-danger col-form-label-sm err", id = "errVDFaxReq", hidden = "hidden" })

            </div>*@
    </div>
    <div class="row">
        <div class="form-group col-6">
            <label for="lblPTelephoneNo" class="control-label field-required">Telephone No :</label>
            @Html.TextBoxFor(model => model.mipd_telephone_no, new { @class = "form-control", @id = "txtPTelephoneNo", @readonly = "readonly" })


        </div>
        <div class="form-group col-6">
            <label for="lblPOccupation" class="control-label field-required">Occupation/Business :</label>
            @Html.TextBoxFor(model => model.mipd_occupation, new { @class = "form-control", @id = "txtPOccupation", @readonly = "readonly" })


        </div>
    </div>
    <div class="row">



        @*<div class="form-group col-6">
                <label for="tblTypeOfCover" class="control-label field-required">Type of Cover :</label>

                @Html.DropDownListFor(Model => Model.mipd_type_of_cover_id,
                                                     new SelectList(Model.mipd_type_of_cover_list, "Value", "Text"),
                                                   "-- Select Type of Cover --",
                                                  new {@id= "ddlTypeofCover", @class = "form-control"})
                @Html.ValidationMessageFor(m => m.mipd_type_of_cover, "Please select type of cover.", new { @class = "text-danger col-form-label-sm err", id = "errddlTypeofCoverReq", hidden = "hidden" })
            </div>*@
    </div>
    @if (Model.mipd_pagetype == "Renewal" || Model.mipd_pagetype == "EditRenewal")
    {
        <div class="row" style="display:none">
            <div class="form-group col-6">
                <label for="lblPTelephoneNo" class="control-label field-required">Previous Reference No :</label>
                @Html.TextBoxFor(model => model.mipd_old_application_Ref_number, new { @class = "form-control", @id = "txtPrevRefNo", @readonly = "readonly" })


            </div>
            <div class="form-group col-6" style="display:none">
                <label for="lblPolicyMonths" class="control-label field-required"></label>
                @Html.TextBoxFor(model => model.PolicyMonths, new { @class = "form-control", @id = "txtPolicyMonths", @readonly = "readonly" })
            </div>
        </div>
    }
</div>
<script type="text/javascript">

    $(document).ready(function () {
        
        

        if ($("#hdnPagetype").val() == "Renewal" || $("#hdnPagetype").val() == "EditRenewal") {
            $("#divMIProposerDetails").find("input, button, submit, textarea").attr('readonly', true);
            
        }
        else {
            
            $('#txtPAddress').prop('readonly', false);
            $('#txtPFaxNo').prop('readonly', false);
            $('#txtPPinCode').prop('readonly', false);
        }
       
        if ($("#txtOwnerofVehicle").val() == "") {
            $("#txtOwnerofVehicle").attr("readonly", false);  
            $("#txtOwnerofVehicle").removeAttr("style");
        }
        else {
            //alert("1");
            $('#txtOwnerofVehicle').prop('readonly', true);
           
        }
       
        
        //$('input[type="text"]').val() == "" ? $('input[type="text"]').removeAttr('readonly') : "";
        $.each($('input[type="text"]'), function () {
            if ($.trim($(this).val()) == "") { $(this).removeAttr('readonly'); }
        })

        var RefNumber = $("#hdnMIReferanceNo").val();
        if (RefNumber != null) {
            $("#spnMIReferanceNo").text(RefNumber);
        }
        
        EnableDisableNexrButton();

        if ($('#txtPAddress').val() != "") {
            $('#txtPAddress').prop('readonly', true);
        }
        if ($('#txtPPinCode').val() == "0") {

            $('#txtPPinCode').removeAttr("readonly");
            $('#txtPPinCode').removeAttr("style");
        }
        if ($("#txtPEmail").val() == "" || $("txtPEmail").val() == null) {
            $('#txtPEmail').removeAttr("readonly");
            $('#txtPEmail').removeAttr("style");
            //alert($("#txtPEmail").val());
            //$("#txtPEmail").attr("readonly", false);
        }
        //else {
        //    $('#txtPAddress').prop('readonly', false);
        //}

        //if ($('#txtPFaxNo').val() != "0") {
        //    $('#txtPFaxNo').prop('readonly', true);

        //}
        //else {
           
        //    $('#txtPFaxNo').prop('readonly', false);
        //}

        

    });

    $('.ClNum').keyup(function () {
        var input_val = $(this).val();
        var inputRGEX = /^[0-9]*$/;
        var inputResult = inputRGEX.test(input_val);
        if (!(inputResult)) {
            this.value = this.value.replace(/[^0-9\s]/gi, '');
        }

    });

   
</script>